export const DATA1 = [
  {
    company: 'OneAdvanced',
    department: 'CSPIT (IT)',
    id: '17IT011',
    firstName: 'PRANAV',
    lastName: 'BHUCHHADA',
    package: 6.0,
    year: 2020,
  },
  {
    company: 'Tatvasoft',
    department: 'CSPIT (IT)',
    id: '17IT013',
    firstName: 'DHARMESH',
    lastName: 'CHAUHAN',
    package: 3.24,
    year: 2020,
  },
  {
    company: 'CrestData',
    department: 'CSPIT (IT)',
    id: '17IT015',
    firstName: 'KISHAN',
    lastName: 'DALSANIA',
    package: 4.5,
    year: 2020,
  },
  {
    company: 'Harikrupa Automation Pvt Ltd',
    department: 'CSPIT (IT)',
    id: '17IT016',
    firstName: 'RAJ',
    lastName: 'DAVE',
    package: 3.0,
    year: 2020,
  },
  {
    company: 'CrestData',
    department: 'CSPIT (IT)',
    id: '17IT020',
    firstName: 'ANKIT',
    lastName: 'DETROJA',
    package: 3.5,
    year: 2020,
  },
  {
    company: 'Tatvasoft',
    department: 'CSPIT (IT)',
    id: '17IT024',
    firstName: 'JAY',
    lastName: 'DOSHI',
    package: 3.6,
    year: 2020,
  },
  {
    company: 'OneAdvanced',
    department: 'CSPIT (IT)',
    id: '17IT028',
    firstName: 'AKSHAY',
    lastName: 'GELANI',
    package: 6.0,
    year: 2020,
  },
  {
    company: 'Gateway',
    department: 'CSPIT (IT)',
    id: '17IT029',
    firstName: 'MAULIK',
    lastName: 'GEVARIYA',
    package: 3.3,
    year: 2020,
  },
  {
    company: 'Tatvasoft',
    department: 'CSPIT (IT)',
    id: '17IT031',
    firstName: 'AKSHAR',
    lastName: 'GOTHI',
    package: 3.24,
    year: 2020,
  },
  {
    company: 'Tatvasoft',
    department: 'CSPIT (IT)',
    id: '17IT032',
    firstName: 'ARPIT',
    lastName: 'GOTHI',
    package: 3.6,
    year: 2020,
  },
  {
    company: 'Bacancy Technology',
    department: 'CSPIT (IT)',
    id: '17IT033',
    firstName: 'DHRUV',
    lastName: 'INTWALA',
    package: 3.0,
    year: 2020,
  },
  {
    company: 'CrestData',
    department: 'CSPIT (IT)',
    id: '17IT035',
    firstName: 'DIRGH',
    lastName: 'JANI',
    package: 4.5,
    year: 2020,
  },
  {
    company: 'Gateway',
    department: 'CSPIT (IT)',
    id: '17IT037',
    firstName: 'VEDANSHUBHAI',
    lastName: 'JOSHI',
    package: 4.2,
    year: 2020,
  },
  {
    company: 'TCS (Codevita)',
    department: 'CSPIT (IT)',
    id: '17IT040',
    firstName: 'ABHI',
    lastName: 'KAILA',
    package: 4.5,
    year: 2020,
  },
  {
    company: 'CrestData',
    department: 'CSPIT (IT)',
    id: '17IT041',
    firstName: 'JAY',
    lastName: 'KANANI',
    package: 4.5,
    year: 2020,
  },
  {
    company: 'CrestData',
    department: 'CSPIT (IT)',
    id: '17IT043',
    firstName: 'DIXIT',
    lastName: 'KAPURIYA',
    package: 4.5,
    year: 2020,
  },
  {
    company: 'Simform',
    department: 'CSPIT (IT)',
    id: '17IT048',
    firstName: 'UJAS',
    lastName: 'MAJITHIYA',
    package: 3.6,
    year: 2020,
  },
  {
    company: ' TCS (Codevita)',
    department: 'CSPIT (IT)',
    id: '17IT049',
    firstName: 'JAYMEET',
    lastName: 'MEHTA',
    package: 4.5,
    year: 2020,
  },
  {
    company: 'Bacancy Technology',
    department: 'CSPIT (IT)',
    id: '17IT050',
    firstName: 'JEET',
    lastName: 'MEHTA',
    package: 3.0,
    year: 2020,
  },
  {
    company: 'TCS (Codevita)',
    department: 'CSPIT (IT)',
    id: '17IT051',
    firstName: 'MANN',
    lastName: 'MEHTA',
    package: 4.5,
    year: 2020,
  },
  {
    company: 'Simform',
    department: 'CSPIT (IT)',
    id: '17IT053',
    firstName: 'MEET',
    lastName: 'MISTRY',
    package: 3.6,
    year: 2020,
  },
  {
    company: 'Simform',
    department: 'CSPIT (IT)',
    id: '17IT055',
    firstName: 'JIGAR',
    lastName: 'MODI',
    package: 3.6,
    year: 2020,
  },
  {
    company: 'Jeavio',
    department: 'CSPIT (IT)',
    id: '17IT056',
    firstName: 'ROHAN',
    lastName: 'MODI',
    package: 5.5,
    year: 2020,
  },
  {
    company: 'OpenXcell',
    department: 'CSPIT (IT)',
    id: '17IT057',
    firstName: 'AMAN',
    lastName: 'MUNDHVA',
    package: 2.64,
    year: 2020,
  },
  {
    company: 'Cybercom',
    department: 'CSPIT (IT)',
    id: '17IT060',
    firstName: 'CHANDNI',
    lastName: 'PARIKH',
    package: 3.12,
    year: 2020,
  },
  {
    company: 'CrestData',
    department: 'CSPIT (IT)',
    id: '17IT062',
    firstName: 'NEVIL',
    lastName: 'PARIKH',
    package: 3.5,
    year: 2020,
  },
  {
    company: 'CrestData',
    department: 'CSPIT (IT)',
    id: '17IT065',
    firstName: 'VATSALSINH',
    lastName: 'PARMAR',
    package: 4.5,
    year: 2020,
  },
  {
    company: 'Tatvasoft',
    department: 'CSPIT (IT)',
    id: '17IT066',
    firstName: 'CHINTANKUMAR',
    lastName: 'PATEL',
    package: 3.6,
    year: 2020,
  },
  {
    company: 'Bacancy Technology',
    department: 'CSPIT (IT)',
    id: '17IT067',
    firstName: 'DHARVIBEN',
    lastName: 'PATEL',
    package: 3.0,
    year: 2020,
  },
  {
    company: 'CrestData',
    department: 'CSPIT (IT)',
    id: '17IT075',
    firstName: 'PRACHI',
    lastName: 'PATEL',
    package: 4.5,
    year: 2020,
  },
  {
    company: 'Einfochips',
    department: 'CSPIT (IT)',
    id: '17IT080',
    firstName: 'UJASKUMAR',
    lastName: 'PATEL',
    package: 3.6,
    year: 2020,
  },
  {
    company: 'CrestData',
    department: 'CSPIT (IT)',
    id: '17IT084',
    firstName: 'NAYAN',
    lastName: 'PATIL',
    package: 4.5,
    year: 2020,
  },
  {
    company: 'Tatvasoft',
    department: 'CSPIT (IT)',
    id: '17IT085',
    firstName: 'AMIKUMARI',
    lastName: 'PRAJAPATI',
    package: 3.6,
    year: 2020,
  },
  {
    company: 'Tatvasoft',
    department: 'CSPIT (IT)',
    id: '17IT086',
    firstName: 'DHARMIL',
    lastName: 'PRAJAPATI',
    package: 3.24,
    year: 2020,
  },
  {
    company: 'CrestData',
    department: 'CSPIT (IT)',
    id: '17IT087',
    firstName: 'MEGHANSHI',
    lastName: 'PRAJAPATI',
    package: 4.5,
    year: 2020,
  },
  {
    company: 'Surekha Technologies',
    department: 'CSPIT (IT)',
    id: '17IT088',
    firstName: 'PREYANSH',
    lastName: 'PRAJAPATI',
    package: 3.0,
    year: 2020,
  },
  {
    company: 'CrestData',
    department: 'CSPIT (IT)',
    id: '17IT089',
    firstName: 'DIVYESH',
    lastName: 'RABADIYA',
    package: 4.5,
    year: 2020,
  },
  {
    company: 'Einfochips',
    department: 'CSPIT (IT)',
    id: '17IT090',
    firstName: 'AVANITKUMAR',
    lastName: 'RACHHADIYA',
    package: 3.6,
    year: 2020,
  },
  {
    company: 'CrestData',
    department: 'CSPIT (IT)',
    id: '17IT093',
    firstName: 'MAULIK',
    lastName: 'RAMANI',
    package: 4.5,
    year: 2020,
  },
  {
    company: 'TCS (Codevita)',
    department: 'CSPIT (IT)',
    id: '17IT097',
    firstName: 'RUTVIK',
    lastName: 'RUPAPARA',
    package: 4.2,
    year: 2020,
  },
  {
    company: 'CrestData',
    department: 'CSPIT (IT)',
    id: '17IT099',
    firstName: 'ARADHI',
    lastName: 'SADRANI',
    package: 4.5,
    year: 2020,
  },
  {
    company: 'Einfochips',
    department: 'CSPIT (IT)',
    id: '17IT105',
    firstName: 'JAPAN',
    lastName: 'SHAH',
    package: 3.6,
    year: 2020,
  },
  {
    company: 'CrestData',
    department: 'CSPIT (IT)',
    id: '17IT106',
    firstName: 'KUNJ',
    lastName: 'SHAH',
    package: 4.5,
    year: 2020,
  },
  {
    company: 'Gateway',
    department: 'CSPIT (IT)',
    id: '17IT109',
    firstName: 'MOHIT',
    lastName: 'SOJITRA',
    package: 3.0,
    year: 2020,
  },
  {
    company: 'Gateway',
    department: 'CSPIT (IT)',
    id: '17IT114',
    firstName: 'RAHULKUMAR',
    lastName: 'TANK',
    package: 4.2,
    year: 2020,
  },
  {
    company: 'Teksun',
    department: 'CSPIT (IT)',
    id: '17IT115',
    firstName: 'MAYUR',
    lastName: 'TELI',
    package: 2.1,
    year: 2020,
  },
  {
    company: 'Meditab',
    department: 'CSPIT (IT)',
    id: '17IT118',
    firstName: 'JANAK',
    lastName: 'THUMMAR',
    package: 3.6,
    year: 2020,
  },
  {
    company: 'Gateway',
    department: 'CSPIT (IT)',
    id: '17IT120',
    firstName: 'MALHAR',
    lastName: 'TRIVEDI',
    package: 4.2,
    year: 2020,
  },
  {
    company: 'CrestData',
    department: 'CSPIT (IT)',
    id: '17IT124',
    firstName: 'MISHAR',
    lastName: 'VADODARIA',
    package: 4.5,
    year: 2020,
  },
  {
    company: 'CrestData',
    department: 'CSPIT (IT)',
    id: '17IT127',
    firstName: 'NIKET',
    lastName: 'VANIA',
    package: 4.5,
    year: 2020,
  },
  {
    company: 'Synoverge Technologies Pvt. Ltd',
    department: 'CSPIT (IT)',
    id: '17IT130',
    firstName: 'RIYA',
    lastName: 'VORA',
    package: 3.3,
    year: 2020,
  },
  {
    company: 'Tatvasoft',
    department: 'CSPIT (IT)',
    id: '17IT131',
    firstName: 'YUVRAJSINH',
    lastName: 'ZALA',
    package: 3.6,
    year: 2020,
  },
  {
    company: 'Gateway',
    department: 'CSPIT (IT)',
    id: 'D18IT132',
    firstName: 'HARDI',
    lastName: 'MEHTA',
    package: 4.2,
    year: 2020,
  },
  {
    company: 'OpenXcell',
    department: 'CSPIT (IT)',
    id: 'D18IT133',
    firstName: 'NANDINI',
    lastName: 'BHATT',
    package: 2.76,
    year: 2020,
  },
  {
    company: 'OpenXcell',
    department: 'CSPIT (IT)',
    id: 'D18IT135',
    firstName: 'KEVALKUMAR',
    lastName: 'SHAH',
    package: 2.16,
    year: 2020,
  },
];
